/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.LoansReportController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;
import javax.swing.table.DefaultTableModel;
import view.resources.classes.TextBubbleBorder;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
/**
 *
 * @author Clara Elizabeth
 */
public class LoansReports extends javax.swing.JFrame {

    private DefaultTableModel model;
    private ArrayList<Object[]> genders;
    private ArrayList<Object[]> loans;
    private ArrayList<String> gendersActivated;
    private LoansReportController controller;
    private String codeLogIn;
    private String filterUser = "";
    private String filterBook = "";
    private String filterLoanDate = "";
    private String filterReturnDate = "";
    private String filterStatus = "";
    private AbstractBorder borderBlack = new TextBubbleBorder(Color.black,2,6,0); 
    private AbstractBorder borderWhite = new TextBubbleBorder(Color.white,2,6,0);     
    
    /**
     * Creates new form viewCategory
     * @param code
     */
    public LoansReports(String code) {
        initComponents();
        System.out.println(jLabel7.getBounds());
        filterByUser.setBorder(borderBlack);
        filterByBook.setBorder(borderBlack);
        filterByLoanDate.setBorder(borderBlack);
        filterByReturn.setBorder(borderBlack);        
        filterByStatus.setBorder(borderBlack);
        codeLogIn = code;
        controller = new LoansReportController();
        model = (DefaultTableModel) JTblCategoria.getModel();
        genders = controller.searchGender(-1);
        loans = controller.tableContent("");
        gendersActivated = new ArrayList<>();
        addCategories();
        updateTable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblCategoria = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBtnVolver = new javax.swing.JButton();
        filterByUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filterByBook = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filterByLoanDate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filterByReturn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filterByStatus = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 237, 205));

        JTblCategoria.setBackground(new java.awt.Color(204, 213, 174));
        JTblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Usuario", "ID Usuario", "Nombre Libro", "Fecha Prestamo", "Fecha Devolucion", "Categoria", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTblCategoria);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(204, 213, 174));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        jLabel1.setText("Categorias");

        JBtnVolver.setBackground(new java.awt.Color(212, 163, 115));
        JBtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/resources/imgs/backIcon.png"))); // NOI18N
        JBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVolverActionPerformed(evt);
            }
        });

        filterByUser.setBackground(new java.awt.Color(204, 213, 174));
        filterByUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterByUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filterByUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                filterByUserMouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filtrar por usuario");

        javax.swing.GroupLayout filterByUserLayout = new javax.swing.GroupLayout(filterByUser);
        filterByUser.setLayout(filterByUserLayout);
        filterByUserLayout.setHorizontalGroup(
            filterByUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterByUserLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterByUserLayout.setVerticalGroup(
            filterByUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterByUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel3.setText("Filtros:");

        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        filterByBook.setBackground(new java.awt.Color(204, 213, 174));
        filterByBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterByBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filterByBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                filterByBookMouseExited(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Filtrar por libro");

        javax.swing.GroupLayout filterByBookLayout = new javax.swing.GroupLayout(filterByBook);
        filterByBook.setLayout(filterByBookLayout);
        filterByBookLayout.setHorizontalGroup(
            filterByBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterByBookLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterByBookLayout.setVerticalGroup(
            filterByBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterByBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterByLoanDate.setBackground(new java.awt.Color(204, 213, 174));
        filterByLoanDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterByLoanDateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filterByLoanDateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                filterByLoanDateMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha prestamo");

        javax.swing.GroupLayout filterByLoanDateLayout = new javax.swing.GroupLayout(filterByLoanDate);
        filterByLoanDate.setLayout(filterByLoanDateLayout);
        filterByLoanDateLayout.setHorizontalGroup(
            filterByLoanDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterByLoanDateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );
        filterByLoanDateLayout.setVerticalGroup(
            filterByLoanDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterByLoanDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterByReturn.setBackground(new java.awt.Color(204, 213, 174));
        filterByReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterByReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filterByReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                filterByReturnMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha devolucion");

        javax.swing.GroupLayout filterByReturnLayout = new javax.swing.GroupLayout(filterByReturn);
        filterByReturn.setLayout(filterByReturnLayout);
        filterByReturnLayout.setHorizontalGroup(
            filterByReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterByReturnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );
        filterByReturnLayout.setVerticalGroup(
            filterByReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterByReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterByStatus.setBackground(new java.awt.Color(204, 213, 174));
        filterByStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterByStatusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filterByStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                filterByStatusMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Estado");

        javax.swing.GroupLayout filterByStatusLayout = new javax.swing.GroupLayout(filterByStatus);
        filterByStatus.setLayout(filterByStatusLayout);
        filterByStatusLayout.setHorizontalGroup(
            filterByStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterByStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(49, 49, 49))
        );
        filterByStatusLayout.setVerticalGroup(
            filterByStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterByStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(filterByLoanDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(filterByUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(filterByReturn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(filterByBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(filterByStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(152, 152, 152))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(238, 238, 238))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(JBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(JBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filterByUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterByBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(filterByLoanDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterByReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterByStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVolverActionPerformed
        // TODO add your handling code here:

        ReportMenu menu = new ReportMenu(codeLogIn);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnVolverActionPerformed

    private void filterByUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByUserMouseClicked
        // TODO add your handling code here:
        if("".equals(filterUser) || filterUser == null){
            filterUser = JOptionPane.showInputDialog(this, "Ingrese el codigo del usuario");
            if((!"".equals(filterUser)) && filterUser != null){              
                updateTable(false);
                filterUser += "";
                jLabel2.setText(filterUser);
                int width = filterUser.length() * 7;
                jLabel2.setBounds(15, 6, width, 16); 
            }
        }else{
            jLabel2.setText("Filtar por usuario");
            jLabel2.setBounds(15, 6, 97, 16);
            filterUser = "";
            updateTable(false);
        }
    }//GEN-LAST:event_filterByUserMouseClicked

    private void filterByUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByUserMouseEntered
        // TODO add your handling code here:
        filterByUser.setBorder(borderWhite);
    }//GEN-LAST:event_filterByUserMouseEntered

    private void filterByUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByUserMouseExited
        // TODO add your handling code here:
        filterByUser.setBorder(borderBlack);        
    }//GEN-LAST:event_filterByUserMouseExited

    private void filterByLoanDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByLoanDateMouseClicked
        // TODO add your handling code here:
        if("".equals(filterLoanDate) || filterLoanDate == null){
            filterLoanDate = JOptionPane.showInputDialog(this, "Ingrese el codigo del usuario");
            if(!("".equals(filterLoanDate)) && (filterLoanDate != null)){
                updateTable(false);
                filterLoanDate += "";
                jLabel4.setText(filterLoanDate);
                int width = filterLoanDate.length() * 7;
                jLabel4.setBounds(20, 6, width, 16);
            }
        }else{
            jLabel4.setText("Filtar prestamo");
            jLabel4.setBounds(20, 6, 90, 16);
            filterLoanDate = "";
            updateTable(false);

        }
    }//GEN-LAST:event_filterByLoanDateMouseClicked

    private void filterByLoanDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByLoanDateMouseEntered
        // TODO add your handling code here:
        filterByLoanDate.setBorder(borderWhite);
    }//GEN-LAST:event_filterByLoanDateMouseEntered

    private void filterByLoanDateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByLoanDateMouseExited
        // TODO add your handling code here:
        filterByLoanDate.setBorder(borderBlack);
    }//GEN-LAST:event_filterByLoanDateMouseExited

    private void filterByReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByReturnMouseClicked
        // TODO add your handling code here:
        if("".equals(filterReturnDate) || filterReturnDate == null){
            filterReturnDate = JOptionPane.showInputDialog(this, "Ingrese el codigo del usuario");
            if(!("".equals(filterReturnDate)) && (filterReturnDate != null)){
                updateTable(false);
                filterReturnDate += "";
                jLabel5.setText(filterReturnDate);
                int width = filterReturnDate.length() * 7;
                jLabel5.setBounds(20, 6, width, 16);
            }
        }else{
            jLabel5.setText("Filtar devolucion");
            jLabel5.setBounds(20, 6, 96, 16);
            filterReturnDate = "";
            updateTable(false);
        }
    }//GEN-LAST:event_filterByReturnMouseClicked

    private void filterByReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByReturnMouseEntered
        // TODO add your handling code here:
        filterByReturn.setBorder(borderWhite);
    }//GEN-LAST:event_filterByReturnMouseEntered

    private void filterByReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByReturnMouseExited
        // TODO add your handling code here:
        filterByReturn.setBorder(borderBlack);
    }//GEN-LAST:event_filterByReturnMouseExited

    private void filterByBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByBookMouseClicked
        // TODO add your handling code here:
        if ("".equals(filterBook) || filterBook == null) {
            filterBook = JOptionPane.showInputDialog(this, "Ingrese el codigo del usuario");
            if (!("".equals(filterBook)) && (filterBook != null)) {
                updateTable(false);
                filterBook += "";
                jLabel6.setText(filterBook);
                int width = filterBook.length() * 7;
                jLabel6.setBounds(20, 6, width, 16);
            }
        } else {
            jLabel6.setText("Filtar por libro");
            jLabel6.setBounds(20, 6, 79, 16);
            filterBook = "";
            updateTable(false);
        }
    }//GEN-LAST:event_filterByBookMouseClicked

    private void filterByBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByBookMouseEntered
        // TODO add your handling code here:
        filterByBook.setBorder(borderWhite);
    }//GEN-LAST:event_filterByBookMouseEntered

    private void filterByBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByBookMouseExited
        // TODO add your handling code here:
        filterByBook.setBorder(borderBlack);
    }//GEN-LAST:event_filterByBookMouseExited

    private void filterByStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByStatusMouseClicked
        // TODO add your handling code here:
        if ("".equals(filterStatus) || filterStatus == null) {
            filterStatus = JOptionPane.showInputDialog(this, "Ingrese el estado del prestamo");
            if (!("".equals(filterStatus)) && (filterStatus != null)) {
                updateTable(false);
                filterStatus += "";
                jLabel7.setText(filterStatus);
                int width = filterStatus.length() * 7;
                jLabel7.setBounds(15, 6, width, 16);
            }
        } else {
            jLabel7.setText("Estado");
            jLabel7.setBounds(48, 6, 39, 16);
            filterStatus = "";
            updateTable(false);
        }
    }//GEN-LAST:event_filterByStatusMouseClicked

    private void filterByStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByStatusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_filterByStatusMouseEntered

    private void filterByStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterByStatusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_filterByStatusMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        String nombre = JOptionPane.showInputDialog(this, "Ingerse el nombre del arichivo");
        try {
            // Obtener la ruta del directorio de inicio del usuario
            String ruta = System.getProperty("user.home");

            // Crear un escritor PDF que escribirá en un archivo en el escritorio del usuario
            PdfWriter.getInstance(documento, new FileOutputStream(ruta+"/Downloads/"+nombre+".pdf"));
            // Abrir el documento para escribir en él
            documento.open();

            // Crear una tabla con 3 columnas
            PdfPTable tabla = new PdfPTable(7);

            // Agregar encabezados a la tabla
            tabla.addCell("Nombre Usuario");
            tabla.addCell("ID Usuario");
            tabla.addCell("Nombre Libro");
            tabla.addCell("Fecha prestamo");
            tabla.addCell("Fecha devolucion");
            tabla.addCell("Categoria");
            tabla.addCell("Estado");

            // Agregar datos de un estudiante a la tabla
            for (int i = 0; i < model.getRowCount(); i++) {
                tabla.addCell(model.getValueAt(i, 0).toString());
                tabla.addCell(model.getValueAt(i, 1).toString());
                tabla.addCell(model.getValueAt(i, 2).toString());
                tabla.addCell(model.getValueAt(i, 3).toString());
                tabla.addCell(model.getValueAt(i, 4).toString());
                tabla.addCell(model.getValueAt(i, 5).toString());
                tabla.addCell(model.getValueAt(i, 6).toString());
                

            }

            // Agregar la tabla al documento PDF
            documento.add(tabla);

            // Cerrar el documento PDF
            documento.close();

            // Mostrar un mensaje emergente de notificación
            JOptionPane.showMessageDialog(this, "Reporte creado.");
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JCheckBox category = (JCheckBox) evt.getSource();
        if(category.isSelected()){
            gendersActivated.add(category.getText());            
        }else{
            gendersActivated.remove(category.getText());
            if(gendersActivated.isEmpty()){
                updateTable(true);
                return;
            }
        }
        updateTable(false);
    }
    
    private void addCategories(){                        
        for (int i = 0; i < genders.size(); i++) {
            JCheckBox category = new JCheckBox(genders.get(i)[1].toString());
            category.setBounds(6, i*25 + 10, 190, 25);
            category.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    genderActionPerformed(evt);
                }
            });
            jPanel2.add(category);
        }
    }
    
    private void updateTable(boolean searchType){
        try {
            for (int i = 0; i < 10; i++) {
                for (int j = 0; j < model.getRowCount(); j++) {
                    model.removeRow(j);
                }
            }
        } catch (Exception e) {
        }
        if(searchType){
            for (int i = 0; i < loans.size(); i++) {
                model.addRow(loans.get(i));
            }   
        }else{            
            for (int i = 0; i < loans.size(); i++) {
                boolean[] filtros = {true, true, true , true, true, true};
                if(!gendersActivated.isEmpty()){
                    filtros[0] = false;
                    for (int j = 0; j < gendersActivated.size(); j++) {
                        if(loans.get(i)[5].toString().equals(gendersActivated.get(j))){
                            filtros[0] = true;
                        }                                       
                    }
                }
                if(!filterBook.equals("")){
                    if(!loans.get(i)[2].toString().equals(filterBook)){
                        filtros[2] = false;
                    }
                }if(!filterLoanDate.equals("")){
                    if(!loans.get(i)[3].toString().equals(filterLoanDate)){
                        filtros[3] = false;
                    }
                }if(!filterReturnDate.equals("")){
                    if(!loans.get(i)[4].toString().equals(filterReturnDate)){
                        filtros[4] = false;
                    }
                }if(!filterUser.equals("")){
                    if(!loans.get(i)[1].toString().equals(filterUser)){
                        filtros[1] = false;
                    }
                }if(!filterStatus.equals("")){
                    if(!loans.get(i)[6].toString().equals(filterStatus)){
                        filtros[6] = false;
                    }
                }
                boolean finalVal = true;
                for (int j = 0; j < filtros.length; j++) {
                    if(!filtros[j]){
                        finalVal = false;
                    }
                }
                if(finalVal){
                    model.addRow(loans.get(i));
                }
            }
                
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoansReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoansReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoansReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoansReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoansReports("1234").setVisible(true);
            }
        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnVolver;
    private javax.swing.JTable JTblCategoria;
    private javax.swing.JPanel filterByBook;
    private javax.swing.JPanel filterByLoanDate;
    private javax.swing.JPanel filterByReturn;
    private javax.swing.JPanel filterByStatus;
    private javax.swing.JPanel filterByUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
