/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ManageGendersController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Gender;

/**
 *
 * @author Clara Elizabeth
 */
public class ManageCategory extends javax.swing.JFrame {
     private String codeLogIn;
    private SimpleDateFormat year = new SimpleDateFormat("yyyy");
    private ManageGendersController controller;
    private DefaultTableModel model;
    private ArrayList<Object[]> genders;
    /**
     * Creates new form ManageCategory
     */
    public ManageCategory(String code) {
        initComponents();
        model = (DefaultTableModel) JTblCategoria.getModel();
        this.codeLogIn = code;
        controller = new ManageGendersController();
        genders = controller.buscar(-1);
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBtnGuardar = new javax.swing.JButton();
        JBtnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTxtBuscar = new javax.swing.JTextField();
        JTxtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JBtnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JBtnEditar = new javax.swing.JButton();
        JTxtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblCategoria = new javax.swing.JTable();
        JBtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 237, 205));

        jPanel1.setBackground(new java.awt.Color(250, 237, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtnGuardar.setBackground(new java.awt.Color(212, 163, 115));
        JBtnGuardar.setText("Guardar");
        JBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        JBtnEliminar.setBackground(new java.awt.Color(212, 163, 115));
        JBtnEliminar.setText("Eliminar");
        JBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel1.setText("Registrar categoria:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        JTxtBuscar.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 271, -1));

        JTxtCodigo.setEditable(false);
        JTxtCodigo.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 196, -1));

        jLabel3.setText("Codigo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        JBtnBuscar.setBackground(new java.awt.Color(212, 163, 115));
        JBtnBuscar.setText("Buscar");
        JBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        JBtnEditar.setBackground(new java.awt.Color(212, 163, 115));
        JBtnEditar.setText("Editar");
        JBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        JTxtNombre.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 198, -1));

        JTblCategoria.setBackground(new java.awt.Color(204, 213, 174));
        JTblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria"
            }
        ));
        JTblCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTblCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTblCategoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 77, 440, 280));

        JBtnVolver.setBackground(new java.awt.Color(212, 163, 115));
        JBtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/resources/imgs/backIcon.png"))); // NOI18N
        JBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGuardarActionPerformed
        // TODO add your handling code here:
        
        if( JTxtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
            return;
        }
        String Nombre = JTxtNombre.getText();
        Gender gender = new Gender(Nombre);
        controller.guardar(gender);
        genders = controller.buscar(-1);
        updateTable();
    }//GEN-LAST:event_JBtnGuardarActionPerformed

    private void JBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEditarActionPerformed
        // TODO add your handling code here:
        if(JTxtCodigo.getText().isEmpty() || JTxtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
            return;
        }
        int code = Integer.parseInt(JTxtCodigo.getText());
        String nombre = JTxtNombre.getText();
        Gender gender = new Gender(code,nombre);
        controller.editar(gender);
        genders = controller.buscar(-1);
        updateTable();
    }//GEN-LAST:event_JBtnEditarActionPerformed

    private void JBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEliminarActionPerformed
        // TODO add your handling code here:
        
        if(JTxtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
            return;
        }
        int code = Integer.parseInt(JTxtCodigo.getText());
        controller.eliminar(code);
        genders = controller.buscar(-1);
        updateTable();
    }//GEN-LAST:event_JBtnEliminarActionPerformed

    private void JBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVolverActionPerformed
        // TODO add your handling code here:

        Menu menu = new Menu(codeLogIn);
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_JBtnVolverActionPerformed

    private void JBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnBuscarActionPerformed
        // TODO add your handling code here:
        int code = -1;
        if(!JTxtBuscar.getText().isEmpty()){
            code = Integer.parseInt(JTxtBuscar.getText());
        }
        genders = controller.buscar(code);
        updateTable();
    }//GEN-LAST:event_JBtnBuscarActionPerformed

    private void JTblCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTblCategoriaMouseClicked
        // TODO add your handling code here:
        int row = JTblCategoria.getSelectedRow();
        JTxtCodigo.setText(model.getValueAt(row, 0).toString());
        JTxtNombre.setText(model.getValueAt(row, 1).toString());
    }//GEN-LAST:event_JTblCategoriaMouseClicked

    private void updateTable(){
        try {
            for (int i = 0; i < 10; i++) {
                for (int j = 0; j < model.getRowCount(); j++) {
                    model.removeRow(j);
                }
            }
        } catch (Exception e) {
        }
        try {
            for (int i = 0; i < genders.size(); i++) {
                model.addRow(genders.get(i));
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnBuscar;
    private javax.swing.JButton JBtnEditar;
    private javax.swing.JButton JBtnEliminar;
    private javax.swing.JButton JBtnGuardar;
    private javax.swing.JButton JBtnVolver;
    private javax.swing.JTable JTblCategoria;
    private javax.swing.JTextField JTxtBuscar;
    private javax.swing.JTextField JTxtCodigo;
    private javax.swing.JTextField JTxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
