/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ManageBooksController;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import models.Book;


/**
 *
 * @author Clara Elizabeth
 */
public class ManageBooks extends javax.swing.JFrame {
    private String codeLogIn;
    private SimpleDateFormat year = new SimpleDateFormat("yyyy");
    private ManageBooksController controller;
    /**
     * Creates new form ManageBooks
     */
    public ManageBooks(String code) {
        initComponents();
        
        this.codeLogIn = code;
        controller = new ManageBooksController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTxtCodigo = new javax.swing.JTextField();
        JTxtTitulo = new javax.swing.JTextField();
        JTxtPublicacion = new javax.swing.JTextField();
        JTxtEscritor = new javax.swing.JTextField();
        JTxtGenero = new javax.swing.JTextField();
        JTxtCantidad = new javax.swing.JTextField();
        EditBtn = new javax.swing.JButton();
        InsertBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblBooks = new javax.swing.JTable();
        JBtnVolver = new javax.swing.JButton();
        JTxtSearchBar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 237, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setText("Titulo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setText("Escritor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel4.setText("Genero:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setText("Cantidad copias:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel6.setText("Año de publicacion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        JTxtCodigo.setEditable(false);
        JTxtCodigo.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 210, -1));

        JTxtTitulo.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 210, -1));

        JTxtPublicacion.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 210, -1));

        JTxtEscritor.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtEscritor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, -1));

        JTxtGenero.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 210, -1));

        JTxtCantidad.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, -1));

        EditBtn.setBackground(new java.awt.Color(212, 163, 115));
        EditBtn.setText("Editar");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        InsertBtn.setBackground(new java.awt.Color(212, 163, 115));
        InsertBtn.setText("Guardar");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InsertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        SearchBtn.setBackground(new java.awt.Color(212, 163, 115));
        SearchBtn.setText("Buscar");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        DeleteBtn.setBackground(new java.awt.Color(212, 163, 115));
        DeleteBtn.setText("Eliminar");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        JTblBooks.setBackground(new java.awt.Color(204, 213, 174));
        JTblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo", "Escritor", "Genero", "Cantidad", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTblBooks);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        JBtnVolver.setBackground(new java.awt.Color(212, 163, 115));
        JBtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/resources/imgs/backIcon.png"))); // NOI18N
        JBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        JTxtSearchBar.setBackground(new java.awt.Color(204, 213, 174));
        jPanel1.add(JTxtSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
        try {
            // TODO add your handling code here:
            
            if( JTxtTitulo.getText().isEmpty() || JTxtEscritor.getText().isEmpty() || JTxtGenero.getText().isEmpty() || JTxtCantidad.getText().isEmpty() || JTxtPublicacion.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
                return;
            }
            
            String title = JTxtTitulo.getText();
            String writer = JTxtEscritor.getText();
            String gender = JTxtGenero.getText();
            int quantityCopies =  Integer.parseInt(JTxtCantidad.getText());
            String publicationYearS = JTxtPublicacion.getText();
            java.util.Date publicationYearUt = year.parse(publicationYearS);
            Date publicationYear = new java.sql.Date(publicationYearUt.getTime());
            Book book = new Book( title, writer, gender, quantityCopies,publicationYear);
            controller.guardar(book);
        } catch (ParseException ex) {
        }
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        
        if(JTxtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
            return;
        }
        String code = JTxtCodigo.getText();
        controller.eliminar(code);
       
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        try {
            // TODO add your handling code here:
            if(JTxtCodigo.getText().isEmpty() || JTxtTitulo.getText().isEmpty() || JTxtEscritor.getText().isEmpty() || JTxtGenero.getText().isEmpty() || JTxtCantidad.getText().isEmpty() || JTxtPublicacion.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
                return;
            }
            String code = JTxtCodigo.getText();
            String title = JTxtTitulo.getText();
            String writer = JTxtEscritor.getText();
            String gender = JTxtGenero.getText();
            int quantityCopies =  Integer.parseInt(JTxtCantidad.getText());
            String publicationYearS = JTxtPublicacion.getText();
            java.util.Date publicationYearUt = year.parse(publicationYearS);
            Date publicationYear = new java.sql.Date(publicationYearUt.getTime());
            Book book = new Book(code, title, writer, gender, quantityCopies,publicationYear);
            controller.editar(book);
        } catch (ParseException ex) {
        }
    }//GEN-LAST:event_EditBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        if(JTxtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
            return;
        }
         String code = JTxtCodigo.getText();
        Book book = controller.buscar(code);
        JTxtTitulo.setText(book.getTitle());
        JTxtEscritor.setText(book.getWriter());
        JTxtGenero.setText(book.getGender());
        JTxtCantidad.setText(String.valueOf(book.getQuantityCopies()));
        JTxtPublicacion.setText(year.format(book.getPublicationYear()));
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void JBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVolverActionPerformed
        // TODO add your handling code here:
        
        Menu menu = new Menu(codeLogIn);
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_JBtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JButton JBtnVolver;
    private javax.swing.JTable JTblBooks;
    private javax.swing.JTextField JTxtCantidad;
    private javax.swing.JTextField JTxtCodigo;
    private javax.swing.JTextField JTxtEscritor;
    private javax.swing.JTextField JTxtGenero;
    private javax.swing.JTextField JTxtPublicacion;
    private javax.swing.JTextField JTxtSearchBar;
    private javax.swing.JTextField JTxtTitulo;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
