/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Clara Elizabeth
 */
public class Menu extends javax.swing.JFrame {
    private String codeLogIn;
    /**
     * Creates new form Menu
     */
    public Menu(String code) {
        
        
        initComponents();
        
        this.codeLogIn = code;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBtnLibro = new javax.swing.JButton();
        JBtnUsuario = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        JBtnVolver = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        JBtnFilter = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        JBtnLoans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 237, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        JBtnLibro.setBackground(new java.awt.Color(212, 163, 115));
        JBtnLibro.setText("Libro");
        JBtnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLibroActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, -1));

        JBtnUsuario.setBackground(new java.awt.Color(212, 163, 115));
        JBtnUsuario.setText("Usuario");
        JBtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 130, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, 10));

        JBtnVolver.setBackground(new java.awt.Color(212, 163, 115));
        JBtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/resources/imgs/backIcon.png"))); // NOI18N
        JBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, 10));

        jButton1.setBackground(new java.awt.Color(212, 163, 115));
        jButton1.setText("Categoria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 130, 10));

        JBtnFilter.setBackground(new java.awt.Color(212, 163, 115));
        JBtnFilter.setText("Reportes");
        JBtnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnFilterActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 130, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, 10));

        JBtnLoans.setBackground(new java.awt.Color(212, 163, 115));
        JBtnLoans.setText("Prestamos");
        JBtnLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLoansActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnLoans, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLibroActionPerformed
        // TODO add your handling code here:
        
        ManageBooks managebooks = new ManageBooks(codeLogIn);
        managebooks.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnLibroActionPerformed

    private void JBtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnUsuarioActionPerformed
        // TODO add your handling code here:
        
        ManageUsers manageusers = new ManageUsers(codeLogIn);
        manageusers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnUsuarioActionPerformed

    private void JBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVolverActionPerformed
        // TODO add your handling code here:
        
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageCategory managecategory = new ManageCategory(codeLogIn);
        managecategory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBtnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnFilterActionPerformed
        // TODO add your handling code here:
        ReportMenu bf = new ReportMenu(codeLogIn);
        bf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnFilterActionPerformed

    private void JBtnLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLoansActionPerformed
        // TODO add your handling code here:
        LoansMenu lm = new LoansMenu(codeLogIn);
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnLoansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnFilter;
    private javax.swing.JButton JBtnLibro;
    private javax.swing.JButton JBtnLoans;
    private javax.swing.JButton JBtnUsuario;
    private javax.swing.JButton JBtnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
